services:
    app:
        build:
            context: .
            dockerfile: Dockerfile
        image: dunglas/frankenphp
        ports:
            - "80:80" # HTTP
            - "443:443" # HTTPS
            - "443:443/udp" # HTTP/3
        volumes:
            - '.:/app/public'
        networks:
            - tkl
        depends_on:
            - mysql

    mysql:
        image: 'mysql/mysql-server:8.0'
        ports:
            - 33066:3306
        environment:
            MYSQL_ROOT_PASSWORD: password
            MYSQL_ROOT_HOST: '%'
            MYSQL_DATABASE: tinkerlist
            MYSQL_USER: admin
            MYSQL_PASSWORD: mysql
        volumes:
            - 'mysql:/var/lib/mysql'
            - './vendor/laravel/sail/database/mysql/create-testing-database.sh:/docker-entrypoint-initdb.d/10-create-testing-database.sh'
        networks:
            - tkl
        healthcheck:
            test:
                - CMD
                - mysqladmin
                - ping
                - '-p${DB_PASSWORD}'
            retries: 3
            timeout: 5s
networks:
    tkl:
        driver: bridge
volumes:
    mysql:
        driver: local
